sudo: true
dist: trusty

language: node_js
node_js:
  - '8'

services:
  - docker

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

cache: yarn

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - DOCKER_USER=bwsw
    - DOCKER_REPO=cloudstack-ui

install:
 - yarn

before_script:
 - echo $PROXY_CONF | base64 -d > ./proxy-conf.js

script:
 - docker run --rm -v $(pwd):/workspace -w /workspace trion/ng-cli-e2e /bin/bash -ce "npm run e2e"
 - docker stop cloudstack-simulator-e2e

