sudo: true
dist: trusty

language: node_js
node_js:
  - '8'

services:
  - docker

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

cache: yarn

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - DOCKER_USER=bwsw
    - DOCKER_REPO=cloudstack-ui

install:
 - yarn

before_script:
 - echo $PROXY_CONF | base64 -d > ./proxy-conf.js

script:
 - docker run --rm -v $(pwd):/workspace -w /workspace m7ov/node8-chrome:0.1 /bin/bash -ce "npm run webdriver-clean && npm run webdriver-2.35 && npm run e2e-no-update"
 - docker stop cloudstack-simulator-e2e

