sudo: true
dist: trusty

language: node_js
node_js:
  - '8'

services:
  - docker

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

cache: yarn


env:
  global:
    - DOCKER_USER=bwsw
    - DOCKER_REPO=cloudstack-ui

script:
 - ls

