sudo: true
dist: trusty

language: node_js
node_js:
  - '8'

services:
  - docker

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

cache: yarn

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - DOCKER_USER=bwsw
    - DOCKER_REPO=cloudstack-ui

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

before_script:
 - echo $PROXY_CONF | base64 -d > ./proxy-conf.js
 - docker pull cloudstack/simulator
 - docker run --name cloudstack-simulator-e2e -d --rm -p 4201:8080 cloudstack/simulator
 - bash -c 'for i in $(seq 1 50); do TEST_PORT=$(curl --silent 127.0.0.1:4201 | grep HTML); if [ ! -z "$TEST_PORT" ]; then exit 0; fi; echo "5 sec timeout for retry ($i/25) ..."; sleep 5; done'
 - docker exec -ti cloudstack-simulator-e2e python /root/tools/marvin/marvin/deployDataCenter.py -i /root/setup/dev/basic.cfg
 - docker run --rm -v $(pwd):/workspace -w /workspace markadams/chromium-xvfb-js /bin/bash -ce "npm run e2e"
 - docker stop cloudstack-simulator-e2e

script:
 - yarn e2e

